/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_pilli_BorderlessNative */

#ifndef _Included_fr_pilli_BorderlessNative
#define _Included_fr_pilli_BorderlessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_pilli_BorderlessNative
 * Method:    makeWindowsBorderless
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_pilli_BorderlessNative_makeWindowsBorderless
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fr_pilli_BorderlessNative
 * Method:    setWindowDraggable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_fr_pilli_BorderlessNative_setWindowDraggable
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
