/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_pillisan42_BorderlessNative */

#ifndef _Included_io_github_pillisan42_BorderlessNative
#define _Included_io_github_pillisan42_BorderlessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_pillisan42_BorderlessNative
 * Method:    makeWindowsBorderless
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_pillisan42_BorderlessNative_makeWindowsBorderless
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_pillisan42_BorderlessNative
 * Method:    setWindowDraggable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_github_pillisan42_BorderlessNative_setWindowDraggable
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
